name: Validate

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file .devcontainer/Dockerfile --tag devcontainer-python:$(date +%s)

      - name: Merge dev with main branch
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: dev
          target_branch: main
          github_token: ${{ github.token }}
          message: Merging using github actions
